/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.4.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    java
    // Turns our app into a Spring Boot application
    id("org.springframework.boot") version "3.2.4"
    // Manages Spring dependency versions automatically
    id("io.spring.dependency-management") version "1.1.6"
}

group = "org.telemetry"
version = "0.0.1-SNAPSHOT"

java {
    toolchain {
        // Enforcing Java 21
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // The core web server (Includes Tomcat, REST API support)
    implementation("org.springframework.boot:spring-boot-starter-web")

    // For live real-time data streaming later
    implementation("org.springframework.boot:spring-boot-starter-websocket")

    testImplementation("org.springframework.boot:spring-boot-starter-test")

    // Spring Data JPA for database operations
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")

    // MySQL Driver
    runtimeOnly("com.mysql:mysql-connector-j")
}

tasks.withType<Test> {
    useJUnitPlatform()
}